### ISSUE TITLE
Add ability to include C++ files inside Nucleus

### ISSUE THREAD

**Issue by TheNachoBIT** [nucleus-lang/nucleus#12]
If we want OS dependant handlers to work on its own, we need Nucleus to include them without having to do it ourselves.

```
cpp
{
    "Windows.h"
}

# Call from WinAPI.
extern WriteFile(...) -> int;
```

This could've be a good idea to expand upon and add other languages, for example:

```
py
{
    "hello.py"
}

extern HelloFromPython(...) -> int
```

But for now, C++ is enough :)

**Comment by TheWitheredStriker** [comment]
Looks like a good idea! That being said, I'd prefer more elaborate syntax that isn't just the language abbreviation / file extension, for the sake of clarity.

E.g.

```
includes {
    cpp {
         "MyAwesomeHeader.hpp"
    }
}

// Alternatively, using one-liner syntax from C# that I'd like to implement in Nucleus

includes {
    cpp => "MyAwesomeHeader.hpp"
}
```

I believe this method is also better when importing from multiple languages. Compare:

```
cpp {
    "MyAwesomeHeader.hpp"
}

py {
   "MyAwesomeScript.py"
}

func main() -> void {
   doStuff();
}
```

with:

```
includes {
    cpp {
        "MyAwesomeHeader.hpp"
    },

    py {
        "MyAwesomeScript.py"
    }
}

// Or:

includes {
    cpp => "MyAwesomeHeader.hpp",
    py => "MyAwesomeScript.py" 
}
```

Thoughts?

**Comment by TheNachoBIT** [comment]
sure! i like the idea!

**Comment by TheWitheredStriker** [comment]
Awesome!

One question I have based on style preference. Do you prefer it with or without a colon? See below:

```
// WITH
includes {
    cpp: {
    },

    py: {
    }
}

// WITHOUT
includes {
   cpp {
   },
   
   py {
   }
}
```
(NB: If we end up going with the colon, we can use `cpp: "MyAwesomeHeader.hpp"` instead of the lambda `cpp => "MyAwesomeHeader.hpp"`, which we can then reserve for other stuff instead)

**Comment by TheNachoBIT** [comment]
Closing this as completed due to being able to include all files in the .toml

```toml
[imports.cpp]
include = [
	"Nucleus/System/OS/WinAPI.cpp"
]
```
